version: '3'

services:
  dev:
    ports:
      # vitest ports
      - 51204:51204
      - 4173:4173
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /opt/app
    container_name: 'dev'
    volumes:
      - './:/opt/app'
      - /opt/app/node_modules
