import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  learnSidebar: [{type: 'autogenerated', dirName: '.'}],
  communitySidebar: [
    {
      type: 'category',
      label: 'Community Snippets',
      link: { type: 'doc', id: 'community/snippets/index' },
      items: [
        {
          type: 'category',
          label: 'Components / Systems',
          link: { type: 'doc', id: 'community/snippets/components-systems/index' },
          items: [{ type: 'autogenerated', dirName: 'community/snippets/components-systems' }],
        },
        {
          type: 'category',
          label: 'UI/HUD',
          link: { type: 'doc', id: 'community/snippets/ui-hud/index' },
          items: [{ type: 'autogenerated', dirName: 'community/snippets/ui-hud' }],
        },
        {
          type: 'category',
          label: 'Misc/Utilities',
          link: { type: 'doc', id: 'community/snippets/misc-utilities/index' },
          items: [{ type: 'autogenerated', dirName: 'community/snippets/utilities' }],
        },
        {
          type: 'category',
          label: 'Materials/Post Processors',
          link: { type: 'doc', id: 'community/snippets/materials-postprocessors/index' },
          items: [{ type: 'autogenerated', dirName: 'community/snippets/materials' }],
        },
        
      ],
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;